# Permalinks
permalink:           /:title.html

# Setup
title:               RWeekly.org - Blogs to Learn R from the Community
url:                 https://rweekly.org
paginate:            1
baseurl:             ""
nav-baseurl:         "https://rweekly.org"
ampdir: amp
description: Learn R, R tutorials, R resources, blog posts and the latest updates about the statistical programming R language.
post_max: 396+24

incremental: false
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              R Weekly
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rweekly/rweekly.org

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag

pages_list:       
  Feed: '/atom.xml'
  About: '/about'
  All: '/archive'
  Draft: '/draft'